---
# ワークフローの名前
name: Driveクリーンアップテスト

on:
  # GitHubのUIから手動で実行できるようにする
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'ドライラン（実際には削除しない）'
        required: false
        default: true
        type: boolean

jobs:
  drive-cleanup-test:
    runs-on: ubuntu-latest
    name: Driveクリーンアップ動作確認
    # ジョブに与える権限
    permissions:
      # Workload Identity連携によるGoogle Cloudへの認証のために必要
      id-token: write
      # ログ出力のために必要
      contents: read
    steps:
      # ステップ1: リポジトリをチェックアウト
      - name: 1. リポジトリをチェックアウト
        uses: actions/checkout@v4
        with:
          ref: master

      # ステップ2: Workload Identity連携を使用してGoogle Cloudへ認証する
      - name: 2. Google Cloudへ認証
        uses: google-github-actions/auth@v2
        with:
          # GitHub Secretsに設定した値を参照する
          workload_identity_provider: >-
            ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # ステップ3: uvをセットアップする（高速なPythonパッケージマネージャー）
      - name: 3. uvのセットアップ
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: pyproject.toml

      # ステップ4: 依存ライブラリのインストール（本番依存関係のみ）
      - name: 4. 依存ライブラリのインストール
        run: |
          uv sync --no-dev

      # ステップ5: cleanup_drive_storage.pyの実行
      - name: 5. Driveクリーンアップスクリプト実行
        id: cleanup
        run: |
          echo "🧹 Google Driveクリーンアップスクリプトの動作確認を開始します..."
          echo "DRY_RUN=${{ github.event.inputs.dry_run }}" >> $GITHUB_OUTPUT
          
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            echo "📋 ドライランモード: 実際の削除は行いません"
            echo "スクリプトの実行確認のみを行います"
          else
            echo "⚠️ 実際のクリーンアップを実行します"
          fi

          # スクリプトの実行
          uv run python scripts/cleanup_drive_storage.py
        continue-on-error: false

      # ステップ6: 結果の確認とサマリー
      - name: 6. 結果サマリー
        run: |
          echo "📊 Driveクリーンアップテスト完了"
          echo "=========================================="
          echo "実行モード: ${{ github.event.inputs.dry_run == 'true' && 'ドライラン' || '実際のクリーンアップ' }}"
          echo "実行時刻: $(date '+%Y-%m-%d %H:%M:%S UTC')"
          echo "スクリプトパス: scripts/cleanup_drive_storage.py"
          echo "=========================================="
          echo ""
          echo "✅ スクリプトが正常に実行されました"
          echo "詳細な結果は上記のステップログを確認してください"

      # ステップ7: 失敗時の情報提供
      - name: 7. エラー情報（失敗時のみ）
        if: failure()
        run: |
          echo "❌ cleanup_drive_storage.pyの実行でエラーが発生しました"
          echo ""
          echo "考えられる原因:"
          echo "- Google Cloud認証の問題"
          echo "- API権限の不足"
          echo "- スクリプト内のエラー"
          echo ""
          echo "対処方法:"
          echo "1. GitHub Secretsの設定を確認"
          echo "2. Google Cloud APIの有効化を確認"
          echo "3. スクリプトのログを詳細に確認"